#! /bin/bash
set -e
set -u
set -v

if [[ $# -lt 2 ]]; then
   echo "USAGE: ./build-arch.sh name workspace"
   exit 1
fi

export start="`pwd`"
export name="$1"
export workspace="$2"
export date="`date +%Y%m%d`"

rm -rf $start/out/
mkdir -p $start/out/

cd "$workspace/packages/arch"
commit="`git rev-parse HEAD`"

if [[ `fgrep -c "$date Simon Cadman <src@niftiestsoftware.com>" changelog` -lt 1 ]]; then
    mv changelog changelog.old
    echo "$date Simon Cadman <src@niftiestsoftware.com>

        * $date :
          Change: Automatically generated by buildpackage
" > changelog

    cat changelog.old >> changelog
    unlink changelog.old
fi

currentcommit="`git rev-parse HEAD`"

sed -i "s/pkgver=.*/pkgver=$date/g" PKGBUILD
sed -i "s/_gitversion=.*/_gitversion=\"$currentcommit\"/g" PKGBUILD

#eval `gpg-agent --daemon --pinentry-program /usr/bin/pinentry-curses`

if [[ "`whoami`" != 'root'  ]]; then
    echo "Running as `whoami`"
    makepkg --sign -s --noconfirm
    gpg --verify *.pkg.tar.xz.sig
    gpg -o "$name-$date-1-any.pkg.tar.xz.asc" --enarmor *.pkg.tar.xz.sig
    gpg --verify *.pkg.tar.xz.asc
else
    echo "Running as builduser"
    mv "$workspace" "/home/builduser/workspace"
    cd "/home/builduser/workspace/packages/arch"
    chown -R builduser:builduser ./
    sudo -u builduser makepkg --sign -s --noconfirm
    sudo -u builduser gpg --verify *.pkg.tar.xz.sig
    sudo -u builduser gpg -o "$name-$date-1-any.pkg.tar.xz.asc" --enarmor *.pkg.tar.xz.sig
    sudo -u builduser gpg --verify *.pkg.tar.xz.asc
fi


cp *.pkg.tar.xz* $start/out/
echo "Files in `pwd` , upload `ls *.pkg.tar.xz` "
