#! /bin/bash
set -e
if [[ $# -lt 2 ]]; then
   echo "USAGE: ./build-rpm.sh name workspace [arch]"
   exit 1
fi

export start="`pwd`"
export name="$1"
export workspace="$2"
export date="`date +%Y%m%d`"

export arch="noarch"

set -e
set -v

if [[ $3 != ""  ]]; then
	arch=$3
fi

rm -rf $start/out/
mkdir -p $start/out/

rm -rf /tmp/buildpackage/$name-$date
mkdir -p /tmp/buildpackage/$name-$date/rpmbuild
cd /tmp/buildpackage/$name-$date/rpmbuild
mkdir {BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
cd SOURCES
rsync -av "$workspace/" $name-$date/
cd $name-$date 
pwd
ls -al

if [[ `fgrep -c "($date-1)" packages/redhat/SPECS/$name.spec` -lt 1 ]]; then
    # only add stub entry if one doesnt already exist
    sed -i "/\%changelog/a \
- Change: Automatically generated by buildpackage\n" packages/redhat/SPECS/$name.spec
    sed -i "/\%changelog/a \
* `date +%a\ %b\ %d\ %Y`  <src@niftiestsoftware.com> ($date-1)" packages/redhat/SPECS/$name.spec
fi

yum-builddep -y packages/redhat/SPECS/$name.spec
mv packages/redhat/SPECS/$name.spec /tmp/buildpackage/$name-$date/rpmbuild/SPECS/
rm -rf .git packages
cd ..
tar cjf $name-$date.tar.bz2 $name-$date
rm -rf $name-$date
rm -rf $HOME/rpmbuild
mkdir -p $HOME/rpmbuild/SOURCES
mv $name-$date.tar.bz2 $HOME/rpmbuild/SOURCES/
cd ..
rpmbuild -ba --sign SPECS/$name.spec --target $arch -D "_version $date"

# import signing key to rpm
gpg --export --armor > ~/.build-package-temp-pub-key
rpm --import ~/.build-package-temp-pub-key
unlink ~/.build-package-temp-pub-key

rpm -K $HOME/rpmbuild/RPMS/$arch/*.rpm
rpmlint $HOME/rpmbuild/RPMS/$arch/*.rpm || echo "rpmlint errored"

cp $HOME/rpmbuild/RPMS/$arch/*.rpm $start/out/
echo "Files in $HOME/rpmbuild/RPMS , copy to /root/niftyreporpm/$arch/ , run upload and then upload to s3. "
